/datum/unit_test/life_counter_units/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)

	H.Dizzy(30)
	TEST_ASSERT_EQUAL(H.get_counter_units(/datum/status_effect/life_counter/dizziness), 30, "Dizzy(30) must map to 30 counter units")

	H.Dizzy(10)
	TEST_ASSERT_EQUAL(H.get_counter_units(/datum/status_effect/life_counter/dizziness), 30, "Dizzy() must never lower an existing counter")

	H.set_dizziness(5)
	TEST_ASSERT_EQUAL(H.get_counter_units(/datum/status_effect/life_counter/dizziness), 5, "set_dizziness() must lower the counter")

	H.adjust_timed_status_effect(-10 * STATUS_COUNTER_UNIT, /datum/status_effect/life_counter/dizziness)
	TEST_ASSERT(!H.has_status_effect(/datum/status_effect/life_counter/dizziness), "adjusting below zero must remove the effect")

	H.adjust_timed_status_effect(10 * STATUS_COUNTER_UNIT, /datum/status_effect/life_counter/stutter, 5 * STATUS_COUNTER_UNIT)
	TEST_ASSERT_EQUAL(H.get_counter_units(/datum/status_effect/life_counter/stutter), 5, "max_duration must cap the adjusted counter")

/datum/unit_test/life_counter_animal_stutter/Run()
	var/mob/living/simple_animal/A = allocate(/mob/living/simple_animal)
	A.adjust_timed_status_effect(10 * STATUS_COUNTER_UNIT, /datum/status_effect/life_counter/stutter)
	TEST_ASSERT(!A.has_status_effect(/datum/status_effect/life_counter/stutter), "simple animals must refuse the stutter effect")

/datum/unit_test/life_counter_slowdown/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.Slowdown(5)
	TEST_ASSERT(H.has_status_effect(/datum/status_effect/life_counter/slowed), "Slowdown(5) must apply the slowed effect")
	TEST_ASSERT(H.has_movespeed_modifier(MOVESPEED_ID_LIVING_SLOWDOWN_STATUS), "slowed effect must add the movespeed modifier")
	H.remove_status_effect(/datum/status_effect/life_counter/slowed)
	TEST_ASSERT(!H.has_movespeed_modifier(MOVESPEED_ID_LIVING_SLOWDOWN_STATUS), "removing slowed must clear the movespeed modifier")

/datum/unit_test/life_counter_resting_decay/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.Dizzy(500)
	H.set_resting(TRUE, silent = TRUE)
	var/datum/status_effect/life_counter/dizziness/D = H.has_status_effect(/datum/status_effect/life_counter/dizziness)
	TEST_ASSERT_NOTNULL(D, "dizziness effect must exist")
	var/start = D.remaining()
	sleep(65)
	var/drop = start - D.remaining()
	TEST_ASSERT(drop >= 250, "resting must accelerate dizziness decay 5x (dropped [drop]ds in 65ds)")

/datum/unit_test/life_counter_drowsy_sleep_bridge/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.set_timed_status_effect(120 * STATUS_COUNTER_UNIT, /datum/status_effect/life_counter/drowsiness)
	sleep(45)
	TEST_ASSERT(H.has_status_effect(/datum/status_effect/life_counter/eye_blur), "drowsiness ticks must blur the eyes")
	TEST_ASSERT(H.IsSleeping(), "drowsiness at 100+ units must force sleep")

/datum/unit_test/life_counter_blur_freezes_while_blind/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.blur_eyes(10)
	H.adjust_blindness(10)
	TEST_ASSERT(H.is_blind(), "adjust_blindness must make the mob blind")
	var/datum/status_effect/life_counter/eye_blur/B = H.has_status_effect(/datum/status_effect/life_counter/eye_blur)
	TEST_ASSERT_NOTNULL(B, "blur effect must exist")
	var/start_units = B.units()
	sleep(65)
	TEST_ASSERT(!QDELETED(B) && B.units() >= start_units - 1, "blur must not decay while blind (had [start_units], now [QDELETED(B) ? "gone" : B.units()])")

/datum/unit_test/inebriation/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.set_inebriation(50)
	TEST_ASSERT_EQUAL(H.get_inebriation(), 50, "set_inebriation must set strength")
	H.adjust_inebriation(10)
	TEST_ASSERT_EQUAL(H.get_inebriation(), 60, "adjust_inebriation must add strength")
	sleep(45)
	var/decayed = H.get_inebriation()
	TEST_ASSERT(decayed > 0 && decayed < 60, "inebriation must decay exponentially over ticks (at [decayed])")
	H.set_inebriation(0)
	TEST_ASSERT(!H.has_status_effect(/datum/status_effect/inebriated), "zero strength must remove the inebriated effect")

/datum/unit_test/life_counter_fully_heal/Run()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human)
	H.Dizzy(50)
	H.Jitter(50)
	H.adjust_drowsyness(50)
	H.adjust_timed_status_effect(50 * STATUS_COUNTER_UNIT, /datum/status_effect/life_counter/confusion)
	H.blur_eyes(50)
	H.adjust_blindness(50)
	H.fully_heal()
	for(var/path in list(/datum/status_effect/life_counter/dizziness, /datum/status_effect/life_counter/jitter,
		/datum/status_effect/life_counter/drowsiness, /datum/status_effect/life_counter/confusion,
		/datum/status_effect/life_counter/blindness, /datum/status_effect/life_counter/eye_blur))
		TEST_ASSERT(!H.has_status_effect(path), "fully_heal must clear [path]")
